---
driver:
  name: ec2
  region: eu-west-2
  require_chef_type: t2.micro
  subnet_id: subnet-054cacef31a448807
  aws_ssh_key_id: <%= ENV['AWS_SECRET_ACCESS_KEY']%>
  associate_public_ip: true

# provisioner:
#   name: chef_zero
#   # You may wish to disable always updating cookbooks in CI or other testing environments.
#   # For example:
#   #   always_update_cookbooks: <%= !ENV['CI'] %>
#   always_update_cookbooks: true
#   log_level: info
#   client_rb:
#     chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      # - recipe[node::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
